DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS audio_files;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE audio_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  phrase_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  file_path TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id)
);
